version: '3.6'
services:
  urlspider:
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      - CONCURRENT_REQUESTS=32
      - LOG_LEVEL=INFO
      - RETRY_TIMES=2
      - REDIS_HOST=10.245.146.40
      - REDIS_PORT=6379
      #      - REDIS_PASSWORD=None
      - FILTER_HOST=10.245.146.40
      - FILTER_PORT=6379
      #      - FILTER_PASSWORD=None
      - SPLASH_URL=http://10.245.146.40:8050
      - MONGO_HOST=10.245.146.100
      - MONGO_PORT=37017
      - MONGO_DB=ad_data
      - MONGO_USER=manager-rw
      - MONGO_PASSWORD=HITdbManager-rw!
      - MONGO_COLLECTION=data
      - MONGO_REPL=nistmain
      - IMAGES_MIN_HEIGHT=0
      - IMAGES_MIN_WIDTH=90
      - IMAGES_URLS_FIELD=ad_img_urls
      - IMAGES_RESULT_FIELD=ad_img_paths
      - IMAGES_STORE=images/ad
      - SCREENSHOT_DIR=images/screenshots
      - RANDOM_WAIT_INTERVAL_RANGE=20
      - DOWNLOAD_TIMEOUT=30
    command: scrapy crawl AdUrlSpider
  dataspider:
    build: .
    #    image: leeyanzhe/adcrawler
    volumes:
      - ./:/usr/src/app
    environment:
      - CONCURRENT_REQUESTS=32
      - LOG_LEVEL=INFO
      - RETRY_TIMES=2
      - REDIS_HOST=10.245.146.40
      - REDIS_PORT=6379
      #      - REDIS_PASSWORD=None
      - FILTER_HOST=10.245.146.40
      - FILTER_PORT=6379
      #      - FILTER_PASSWORD=None
      - SPLASH_URL=http://10.245.146.40:8050
      - MONGO_HOST=10.245.146.100
      - MONGO_PORT=37017
      - MONGO_DB=ad_data
      - MONGO_USER=manager-rw
      - MONGO_PASSWORD=HITdbManager-rw!
      - MONGO_COLLECTION=data
      - MONGO_REPL=nistmain
      - IMAGES_MIN_HEIGHT=0
      - IMAGES_MIN_WIDTH=90
      - IMAGES_URLS_FIELD=ad_img_urls
      - IMAGES_RESULT_FIELD=ad_img_paths
      - IMAGES_STORE=images/ad
      - SCREENSHOT_DIR=images/screenshots
      - RANDOM_WAIT_INTERVAL_RANGE=20
      - DOWNLOAD_TIMEOUT=30
    command: scrapy crawl AdDataSpider
